server:
  port: 8088
profiles:
  active: dev

mysql:
  host: 127.0.0.1
  username: root
  password: 123456
  dbname: mun
  port: 3306
  maxIdleConns: 10 # 最多空闲连接数
  maxOpenConns: 10 # 最多打开连接数

logger:
  maxAge: 30
  maxSize: 10
  maxBackups: 10
  level: info
  # 默认是当前工作的目录下的`/log/`文件夹，linux也同理，这里的逻辑暂时没写
  path:
  # 是否需要压缩
  compress: false

redis:
  url: localhost:6379
  password: 123456
  DB: 0

jwt:
  tokenExpire: 30 # token过期时间，单位：分钟
  secretKey: 123456